#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PUBLIC_REPOSITORY="Kuanhao-Chao/DeepGeno.watch"
STATE_REPOSITORY="Kuanhao-Chao/DeepGeno.watch-state"
PUBLIC_HTTPS_ORIGIN="https://github.com/Kuanhao-Chao/DeepGeno.watch.git"
PUBLIC_SSH_ORIGIN="git@github.com:Kuanhao-Chao/DeepGeno.watch.git"
STATE_ORIGIN="https://github.com/Kuanhao-Chao/DeepGeno.watch-state.git"
EXPECTED_LOGIN="Kuanhao-Chao"

abort() {
  warn "$1"
  exit 1
}

require_modern_gh() {
  warn "This setup needs a current GitHub CLI with secret, variable, workflow, and run commands."
  say "If Homebrew manages GitHub CLI, run brew upgrade gh in a separate terminal."
  say "Otherwise install the current release from https://cli.github.com/."
  say "Then run hash -r in that terminal and restart this wizard."
  exit 1
}

read_visible() {
  local variable_name="$1" prompt="$2" value=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r value || true
  printf -v "$variable_name" '%s' "$value"
}

validate_state_repository() {
  local metadata
  metadata="$(gh api "repos/$STATE_REPOSITORY" --jq '[.full_name, .private, .fork, .archived, (.default_branch // "")] | @tsv')" || abort "Unable to read the private companion metadata."
  IFS=$'\t' read -r STATE_FULL_NAME STATE_PRIVATE STATE_FORK STATE_ARCHIVED STATE_DEFAULT_BRANCH <<< "$metadata"
  [[ "$STATE_FULL_NAME" == "$STATE_REPOSITORY" ]] || abort "The companion repository identity is not exact."
  [[ "$STATE_PRIVATE" == "true" ]] || abort "The companion repository must remain private."
  [[ "$STATE_FORK" == "false" ]] || abort "The companion repository must not be a fork."
  [[ "$STATE_ARCHIVED" == "false" ]] || abort "The companion repository must not be archived."
  if [[ -n "$STATE_DEFAULT_BRANCH" && "$STATE_DEFAULT_BRANCH" != "main" ]]; then
    abort "A seeded companion repository must use main as its default branch."
  fi
}

render_pin() {
  (
    cd -- "$PUBLIC_ROOT"
    node scripts/github/render-private-ops.mjs \
      --destination "$STATE_ROOT" \
      --repository Kuanhao-Chao/DeepGeno.watch \
      --commit "$PIN"
  )
}

render_repin() {
  (
    cd -- "$PUBLIC_ROOT"
    node scripts/github/render-private-ops.mjs \
      --destination "$STATE_ROOT" \
      --repository Kuanhao-Chao/DeepGeno.watch \
      --commit "$PIN" --repin
  )
}

SEED_PATHS=(
  ".github/actions/bootstrap-engine/action.yml"
  ".github/workflows/ingest.yml"
  ".github/workflows/private-ops-preflight.yml"
  ".github/workflows/summarize.yml"
  ".github/workflows/triage.yml"
  ".gitignore"
  "README.md"
  "data/private/README.md"
  "engine.lock.json"
)

banner "DeepGeno.watch private operations setup"

stage "Preflight GitHub CLI and account"
say "This stage is read-only and must pass before the wizard can create or configure anything."
command -v git >/dev/null 2>&1 || abort "Git is required."
command -v node >/dev/null 2>&1 || abort "Node.js is required."
command -v gh >/dev/null 2>&1 || require_modern_gh

GH_VERSION_LINE="$(gh --version | sed -n '1p')"
GH_MAJOR="$(printf '%s\n' "$GH_VERSION_LINE" | sed -nE 's/^gh version ([0-9]+).*/\1/p')"
[[ "$GH_MAJOR" =~ ^[0-9]+$ ]] || require_modern_gh
if [[ "$GH_MAJOR" -lt 2 ]]; then require_modern_gh; fi

gh secret set --help >/dev/null 2>&1 || require_modern_gh
gh secret list --help >/dev/null 2>&1 || require_modern_gh
gh variable set --help >/dev/null 2>&1 || require_modern_gh
gh workflow run --help >/dev/null 2>&1 || require_modern_gh
gh run list --help >/dev/null 2>&1 || require_modern_gh
gh run watch --help >/dev/null 2>&1 || require_modern_gh
gh repo create --help >/dev/null 2>&1 || require_modern_gh
gh api --help >/dev/null 2>&1 || require_modern_gh
gh auth status >/dev/null 2>&1 || abort "Authenticate GitHub CLI manually outside this wizard, then rerun it."
AUTHENTICATED_LOGIN="$(gh api user --jq .login)"
[[ "$AUTHENTICATED_LOGIN" == "Kuanhao-Chao" ]] || abort "GitHub CLI must be authenticated as Kuanhao-Chao."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[[ "$NODE_MAJOR" =~ ^[0-9]+$ && "$NODE_MAJOR" -ge 22 ]] || abort "Node.js 22 or newer is required."
say "✓ GitHub CLI capabilities, authentication, Git, and Node.js passed."

stage "Create or validate the private companion"
say "The only allowed companion identity is $STATE_REPOSITORY. The public repository remains public."
STATE_LOOKUP=""
if STATE_LOOKUP="$(gh api "repos/$STATE_REPOSITORY" --include 2>&1)"; then
  say "The companion repository already exists; validating its boundary."
elif [[ "$STATE_LOOKUP" == *"HTTP 404"* ]]; then
  say "The companion does not exist. It will be created empty, without a README, license, or ignore file."
  confirm "Create $STATE_REPOSITORY as a private repository?" || abort "No repository was created."
  gh repo create "$STATE_REPOSITORY" --private
else
  abort "The companion lookup failed for a reason other than absence; no creation was attempted."
fi
unset STATE_LOOKUP
validate_state_repository
say "Never connect $STATE_REPOSITORY to Cloudflare. Cloudflare stays connected only to $PUBLIC_REPOSITORY."
confirm "Confirm the companion is private and will never be Cloudflare-connected." || abort "Repository boundary was not confirmed."

stage "Pin, render, and seed the companion"
SCRIPT_DIRECTORY="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PUBLIC_ROOT="$(cd -- "$SCRIPT_DIRECTORY/.." && pwd -P)"
PUBLIC_PARENT="$(dirname -- "$PUBLIC_ROOT")"
STATE_ROOT="$PUBLIC_PARENT/DeepGeno.watch-state"

[[ "$(git -C "$PUBLIC_ROOT" rev-parse --show-toplevel)" == "$PUBLIC_ROOT" ]] || abort "Run this wizard from the canonical public repository checkout."
PUBLIC_CONFIGURED_ORIGIN="$(git -C "$PUBLIC_ROOT" remote get-url origin)"
if [[ "$PUBLIC_CONFIGURED_ORIGIN" != "$PUBLIC_HTTPS_ORIGIN" && "$PUBLIC_CONFIGURED_ORIGIN" != "$PUBLIC_SSH_ORIGIN" ]]; then abort "The public checkout origin must name exactly $PUBLIC_REPOSITORY."; fi
[[ -z "$(git -C "$PUBLIC_ROOT" status --porcelain=v1 --untracked-files=all)" ]] || abort "The public checkout must be clean."
PUBLIC_HEAD="$(git -C "$PUBLIC_ROOT" rev-parse --verify 'HEAD^{commit}')"
PIN="$(gh api "repos/$PUBLIC_REPOSITORY/commits/main" --jq .sha)"
[[ "$PIN" =~ ^[0-9a-f]{40}$ ]] || abort "Public main did not resolve to a literal lowercase 40-hex commit."
VERIFIED_PIN="$(gh api "repos/$PUBLIC_REPOSITORY/git/commits/$PIN" --jq .sha)"
[[ "$VERIFIED_PIN" == "$PIN" ]] || abort "The public commit object could not be verified."
[[ "$PUBLIC_HEAD" == "$PIN" ]] || abort "The clean public checkout HEAD must equal current public main."

if [[ ! -e "$STATE_ROOT" && ! -L "$STATE_ROOT" ]]; then
  git clone "$STATE_ORIGIN" "$STATE_ROOT"
fi
[[ -d "$STATE_ROOT" && ! -L "$STATE_ROOT" ]] || abort "The companion checkout must be a real directory at the standard sibling path."
STATE_CANONICAL="$(cd -- "$STATE_ROOT" && pwd -P)"
[[ "$STATE_CANONICAL" == "$STATE_ROOT" ]] || abort "The companion checkout path must already be canonical."
[[ -d "$STATE_ROOT/.git" ]] || abort "The companion must be a standard clone with a real .git directory; linked worktrees are unsupported."
[[ ! -L "$STATE_ROOT/.git" ]] || abort "The companion .git directory must not be a symlink."
[[ "$(git -C "$STATE_ROOT" rev-parse --show-toplevel)" == "$STATE_ROOT" ]] || abort "The sibling path is not the companion Git root."
STATE_CONFIGURED_ORIGIN="$(git -C "$STATE_ROOT" remote get-url origin)"
[[ "$STATE_CONFIGURED_ORIGIN" == "$STATE_ORIGIN" ]] || abort "The companion origin must be exactly $STATE_ORIGIN."
STATE_CONFIGURED_PUSH_ORIGIN="$(git -C "$STATE_ROOT" remote get-url --push origin)"
[[ "$STATE_CONFIGURED_PUSH_ORIGIN" == "$STATE_ORIGIN" ]] || abort "The companion push origin must be exactly $STATE_ORIGIN."

if git -C "$STATE_ROOT" rev-parse --verify HEAD >/dev/null 2>&1; then
  [[ -z "$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)" ]] || abort "The companion checkout must be clean before rendering."
  [[ "$(git -C "$STATE_ROOT" symbolic-ref --short HEAD)" == "main" ]] || abort "The companion checkout must be on main."
  git -C "$STATE_ROOT" fetch --no-tags origin refs/heads/main:refs/remotes/origin/main
  [[ "$(git -C "$STATE_ROOT" rev-parse 'HEAD^{commit}')" == "$(git -C "$STATE_ROOT" rev-parse 'refs/remotes/origin/main^{commit}')" ]] || abort "The companion checkout must exactly match remote main."
  [[ -f "$STATE_ROOT/engine.lock.json" && ! -L "$STATE_ROOT/engine.lock.json" ]] || abort "A seeded companion must contain a real engine.lock.json."
  CURRENT_PIN="$(node --input-type=module -e 'import { readFileSync } from "node:fs"; const lock = JSON.parse(readFileSync(process.argv[1], "utf8")); process.stdout.write(lock.commit ?? "");' "$STATE_ROOT/engine.lock.json")"
  [[ "$CURRENT_PIN" =~ ^[0-9a-f]{40}$ ]] || abort "The existing engine lock does not contain a literal commit."
  if [[ "$CURRENT_PIN" != "$PIN" ]]; then
    say "Public main advanced from $CURRENT_PIN to $PIN. Only engine.lock.json may change."
    confirm "Repin the companion, commit only engine.lock.json, and non-force push main?" || abort "The existing engine pin was left unchanged."
    git -C "$STATE_ROOT" var GIT_AUTHOR_IDENT >/dev/null 2>&1 || abort "Configure a Git author identity manually, then rerun the wizard."
    render_repin
    [[ "$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)" == " M engine.lock.json" ]] || abort "Repinning changed more than engine.lock.json."
    git -C "$STATE_ROOT" add -- engine.lock.json
    git -C "$STATE_ROOT" commit -m "chore(operations): repin public engine"
    git -C "$STATE_ROOT" push origin HEAD:main
    render_pin
    [[ -z "$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)" ]] || abort "A same-pin repin verification must be a clean no-op."
  else
    render_pin
    [[ -z "$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)" ]] || abort "A same-pin render must be a no-op."
  fi
else
  git -C "$STATE_ROOT" symbolic-ref HEAD refs/heads/main
  git -C "$STATE_ROOT" var GIT_AUTHOR_IDENT >/dev/null 2>&1 || abort "Configure a Git author identity manually, then rerun the wizard."
  render_pin
  SEED_STATUS="$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)"
  for path_to_seed in "${SEED_PATHS[@]}"; do
    [[ "$SEED_STATUS"$'\n' == *"?? $path_to_seed"$'\n'* ]] || abort "Initial render is missing $path_to_seed."
  done
  SEED_LINE_COUNT="$(printf '%s\n' "$SEED_STATUS" | awk 'NF { count += 1 } END { print count + 0 }')"
  [[ "$SEED_LINE_COUNT" -eq "${#SEED_PATHS[@]}" ]] || abort "Initial render contains a path outside the nine-file seed allowlist."
  confirm "Commit exactly the nine rendered seed files and non-force push main?" || abort "Rendered files remain local and uncommitted."
  git -C "$STATE_ROOT" add -- "${SEED_PATHS[@]}"
  git -C "$STATE_ROOT" commit -m "chore(operations): seed private companion"
  git -C "$STATE_ROOT" push origin HEAD:main
  render_pin
  [[ -z "$(git -C "$STATE_ROOT" status --porcelain=v1 --untracked-files=all)" ]] || abort "A same-pin rerun must be a no-op."
fi
validate_state_repository
[[ "$STATE_DEFAULT_BRANCH" == "main" ]] || abort "The seeded companion default branch must be main."

stage "Configure repository and synthesis scopes"
say "Repository variables and environment variables are written only to $STATE_REPOSITORY."
open_url "https://github.com/Kuanhao-Chao/DeepGeno.watch-state/settings/environments"
step "Create an environment named synthesis. Private-repository environment secrets and variables require an eligible paid GitHub plan; if either control is unavailable, stop and upgrade—never move provider keys to repository or public secrets."
step "Restrict synthesis deployment branches and tags to selected branches and tags, with only main allowed."
step "Required reviewers are conditional on private-repository plan support. When available, require the curator as the environment reviewer."
step "Leave Prevent self-review disabled in this single-curator topology; otherwise the curator who initiates a run can deadlock the only approval path."
step "Save the synthesis environment protection rules before continuing."
pause "Press Enter after the protected synthesis environment exists."
confirm "Confirm private-repository environment secrets and variables are available, synthesis is restricted to main, Prevent self-review is disabled, and any required reviewer was added only when this private-repository plan supports it." || abort "Private environment secrets are required. Upgrade to an eligible paid GitHub plan, then rerun; never fall back to repository or public provider secrets."
confirm "Write the fixed initial variables to the private companion?" || abort "No variables were written."
gh variable set DEEPGENO_PUBLIC_REPOSITORY --repo "$STATE_REPOSITORY" --body "$PUBLIC_REPOSITORY"
gh variable set DEEPGENO_CURATOR_GITHUB_LOGIN --repo "$STATE_REPOSITORY" --body "$EXPECTED_LOGIN"
gh variable set DEEPGENO_MAX_SUMMARIES_PER_RUN --repo "$STATE_REPOSITORY" --body "1"
gh variable set DEEPGENO_LIVE_INGESTION_ENABLED --repo "$STATE_REPOSITORY" --body "false"
gh variable set DEEPGENO_MODEL_PROVIDER --env synthesis --repo "$STATE_REPOSITORY" --body "openai"
gh variable set DEEPGENO_MODEL_NAME --env synthesis --repo "$STATE_REPOSITORY" --body "gpt-5.6-terra"
gh variable set DEEPGENO_MODEL_MAX_OUTPUT_TOKENS --env synthesis --repo "$STATE_REPOSITORY" --body "5000"
read_visible CROSSREF_MAILTO_VALUE "Optional Crossref polite-pool email (Enter skips it):"
if [[ -n "$CROSSREF_MAILTO_VALUE" ]]; then
  gh variable set CROSSREF_MAILTO --repo "$STATE_REPOSITORY" --body "$CROSSREF_MAILTO_VALUE"
else
  note "CROSSREF_MAILTO was not configured."
fi
unset CROSSREF_MAILTO_VALUE

open_url "https://platform.openai.com/api-keys"
step "Create a restricted, project-scoped OpenAI key for the selected gpt-5.6-terra synthesis model."
open_url "https://github.com/Kuanhao-Chao/DeepGeno.watch-state/settings/environments/synthesis"
step "Copy OPENAI_API_KEY browser-to-browser into the synthesis environment; never paste it into this terminal."
step "The initial environment must contain exactly OPENAI_API_KEY. ANTHROPIC_API_KEY is an alternative only and must be absent while provider=openai."
open_url "https://github.com/Kuanhao-Chao/DeepGeno.watch-state/settings/secrets/actions"
step "Optionally add OPENALEX_API_KEY as a repository secret browser-to-browser; never paste it into this terminal."
pause "Press Enter after the environment key and any optional OpenAlex key are configured."
SYNTHESIS_SECRET_NAMES="$(gh secret list --env synthesis --repo "$STATE_REPOSITORY" --json name --jq '.[].name')"
[[ "$SYNTHESIS_SECRET_NAMES" == "OPENAI_API_KEY" ]] || abort "The initial synthesis environment must contain exactly OPENAI_API_KEY and no other secret."
unset SYNTHESIS_SECRET_NAMES

stage "Create and install the curator GitHub App"
say "The App is the only durable GitHub identity used by private operations. Workflows mint one-repository tokens per job."
open_url "https://github.com/settings/apps/new"
step "Create a GitHub App for DeepGeno.watch curation under the Kuanhao-Chao account."
step "Disable the webhook. Keep Metadata read-only; grant Contents, Pull requests, and Issues read/write; leave every other permission at no access."
step "After creation, generate exactly one private key and note the Client ID (not the numeric App ID)."
step "Install the App only on the Kuanhao-Chao account and choose only selected repositories."
step "Select exactly DeepGeno.watch-state and DeepGeno.watch—no organization-wide or all-repository installation."
pause "Press Enter after the App is installed on exactly those two repositories and the PEM is downloaded."
confirm "Confirm the App has webhook disabled, only the stated permission ceiling, owner Kuanhao-Chao, and exactly the two selected repositories." || abort "The App boundary was not confirmed."

stage "Persist App client ID and private key"
read_visible APP_CLIENT_ID "Paste the GitHub App Client ID (not App ID):"
[[ "$APP_CLIENT_ID" =~ ^[A-Za-z0-9._-]{8,128}$ ]] || abort "The Client ID format is invalid."
gh variable set DEEPGENO_PUBLIC_APP_CLIENT_ID --repo "$STATE_REPOSITORY" --body "$APP_CLIENT_ID"
unset APP_CLIENT_ID

read_visible PEM_PATH "Paste the absolute path to the downloaded PEM file:"
[[ "$PEM_PATH" == /* ]] || abort "The PEM path must be absolute."
[[ -f "$PEM_PATH" && ! -L "$PEM_PATH" ]] || abort "The PEM must be a non-symlink regular file."
[[ -s "$PEM_PATH" ]] || abort "The PEM file must not be empty."
PEM_PARENT="$(cd -- "$(dirname -- "$PEM_PATH")" && pwd -P)"
PEM_BASENAME="$(basename -- "$PEM_PATH")"
if [[ "$PEM_PARENT" == "/" ]]; then PEM_CANONICAL="/$PEM_BASENAME"; else PEM_CANONICAL="$PEM_PARENT/$PEM_BASENAME"; fi
[[ "$PEM_CANONICAL" == "$PEM_PATH" ]] || abort "The PEM path must be canonical and contain no symlinked ancestor."
gh secret set DEEPGENO_PUBLIC_APP_PRIVATE_KEY --repo "$STATE_REPOSITORY" < "$PEM_PATH"
unset PEM_PATH PEM_PARENT PEM_BASENAME PEM_CANONICAL
say "Remove the downloaded PEM manually after GitHub confirms the secret; this wizard will not delete local files."

stage "Run the scoped private preflight"
STATE_MAIN_SHA="$(gh api "repos/$STATE_REPOSITORY/commits/main" --jq .sha)"
[[ "$STATE_MAIN_SHA" =~ ^[0-9a-f]{40}$ ]] || abort "Private main did not resolve to a literal commit."
PREVIOUS_RUN_ID="$(gh run list --workflow private-ops-preflight.yml --repo "$STATE_REPOSITORY" --branch main --event workflow_dispatch --limit 1 --json databaseId --jq '.[0].databaseId // ""')"
confirm "Dispatch Private operations preflight at private main $STATE_MAIN_SHA?" || abort "The preflight was not dispatched."
gh workflow run private-ops-preflight.yml --repo "$STATE_REPOSITORY" --ref main

PREFLIGHT_RUN_ID=""
PREFLIGHT_HEAD_SHA=""
for attempt in {1..15}; do
  PREFLIGHT_ROW="$(gh run list --workflow private-ops-preflight.yml --repo "$STATE_REPOSITORY" --branch main --event workflow_dispatch --limit 1 --json databaseId,headSha --jq '.[0] | [.databaseId, .headSha] | @tsv')"
  IFS=$'\t' read -r PREFLIGHT_RUN_ID PREFLIGHT_HEAD_SHA <<< "$PREFLIGHT_ROW"
  if [[ -n "$PREFLIGHT_RUN_ID" && "$PREFLIGHT_RUN_ID" != "$PREVIOUS_RUN_ID" ]]; then break; fi
  sleep 2
done
[[ -n "$PREFLIGHT_RUN_ID" ]] || abort "No preflight run appeared."
[[ "$PREFLIGHT_RUN_ID" != "$PREVIOUS_RUN_ID" ]] || abort "The wizard could not identify a distinct new preflight run."
[[ "$PREFLIGHT_HEAD_SHA" == "$STATE_MAIN_SHA" ]] || abort "The new preflight run is not attached to current private main."
gh run watch "$PREFLIGHT_RUN_ID" --repo "$STATE_REPOSITORY" --exit-status
say "✓ The pinned engine and both one-repository App token scopes passed preflight."

stage "Review the cutover gate"
say "This stage changes nothing. Task 5 owns the model probe, controlled scan, first publication, ruleset, and daily-ingestion enablement."
step "Merge the public implementation only after its full local review; require the stable CI / verify check on public main."
step "Confirm $STATE_REPOSITORY is private, on main, and has a green preflight at its current head."
step "Confirm the curator App is installed on exactly the private and public repositories, with no bypass of public branch protection."
step "Confirm synthesis has exactly the selected provider key and DEEPGENO_LIVE_INGESTION_ENABLED is still false."
step "Confirm the public repository contains no operational literature workflows or private state."
step "Keep the existing deepgeno-watch Worker, production URL, and configuration connected only to $PUBLIC_REPOSITORY; never connect the companion."
step "After Task 5 validates cutover, remove legacy DEEPGENO_GITHUB_TOKEN from the public repository in GitHub Settings; deletion is deliberately not executable here."
warn "Do not dispatch live ingestion, merge either human gate, alter the public ruleset, or remove legacy credentials from this wizard."

finish
